language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
  - make travis-install

services:
  - mongodb
script: make travis-run
env:
  global:
  - NODE_ENV=test
  - DB_CONNECTION=mongodb://localhost:27017/church_crm
  - JWT_SECRET=$2a$10$6Bnv6xUyEX7FrAT3Lhp7O.ZuQnP8Lc1dzt9rscG4XohRpz
  - JWT_EXPIRE=3600

before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.createUser({user:"kadismile",pwd:"111222",roles:["readWrite"]});'