language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - mongodb

env:
  global:
  - NODE_ENV=test

before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.createUser({user:"kadismile",pwd:"111222",roles:["readWrite"]});'